### ISSUE TITLE
Figure out how to accept chats with 'unknown' contacts

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/deltachat-cli#24]
In the Android app, the user is asked a question whether he/she wants to accept a chat from user xyz. I'm wondering what the workflow is to handle this properly. Currently, if I send a message to a cli user, it will show up in `Mailbox` which seems to be handled quite differently than a chat group?

cc @r10s

**Comment by ralphtheninja** [comment]
Currently, I have to first manually add a contact and then manually create a group using that contact, before it works as expected. There must be a better way to do this obviously :)

**Comment by r10s** [comment]
these "contact requests" (called "deaddrop messages" internally) pop up as a special chat when retrieving the chatlist using [dc_get_chatlist()](https://deltachat.github.io/api/classdc__context__t.html#a709a7b5b9b606d85f21e988e89d99fef).
i've updated the doc that was missing this aspect, however, not sure if it is much clearer now :)

**Comment by ralphtheninja** [comment]
Testing things out atm and when a message is received from an unknown contact I get the following event:

![screenshot from 2018-08-11 16-27-49](https://user-images.githubusercontent.com/308049/43992775-9efae98a-9d83-11e8-8809-16ae4c2e3185.png)

But there's no chat with id 13. I'm wondering if this `chat_id` should instead be `DC_CHAT_ID_DEADDROP` (i.e. 1).

**Comment by ralphtheninja** [comment]
Actually, it turns out that 13 in this case is _not_ the `chat_id` but the _from id_. So is this a bug or is the docs for `DC_EVENT_MSGS_CHANGED` incorrect? It states that the first parameter is `chat_id`.

https://deltachat.github.io/api/group__DC__EVENT.html#ga0f52cdaad70dd24f7540abda6193cc2d

**Comment by ralphtheninja** [comment]
https://github.com/ralphtheninja/deltachat-cli/commit/d07be95947ff7594c99ede081bb43dc99627d7bb

**Comment by r10s** [comment]
> But there's no chat with id 13. I'm wondering if this chat_id should instead be DC_CHAT_ID_DEADDROP (i.e. 1)?

@ralphtheninja internally, _all_ messages are assigned to chats, however, chats from unknown users may be hidden from the UI, ie. are just not returned by `dc_get_chatlist()`.

so, the `DC_CHAT_ID_DEADDROP` (i.e. 1) is a sort of a virtual chat that contains messages from different chats with different hidden IDs. `DC_CHAT_ID_DEADDROP` is a sort of a view onto all messages that are from unconfirmed contacts. 
for any messages in `DC_CHAT_ID_DEADDROP` the chat can be "unhidden" by calling [`dc_create_chat_by_msg_id()`](https://deltachat.github.io/api/classdc__context__t.html#aa150be55af0f0a7b7f9ed9bb530f78c5) - in the example above, the ID 13 will then returned by `dc_get_chatlist()` - _plus_ the messages belonging to chat 13 are no longer returned by [`dc_get_msgs(context, DC_CHAT_ID_DEADDROP, ...)`](https://deltachat.github.io/api/classdc__context__t.html#a51353ff6b85fa9278d2ec476c3c95eda)

all this is handled by the core, the UI normally has not to worry about these details, however, a better documentation and better log messages seems to be required :)


> Actually, it turns out that 13 in this case is not the chat_id but the from id. So is this a bug or is the docs for DC_EVENT_MSGS_CHANGED incorrect? It states that the first parameter is chat_id.

might be that the IDs are the same coincidentally. the documentation and the source code look correct.
note, that both, `chat_id` and `msg_id` may be set to 0 for `DC_EVENT_MSGS_CHANGED`.
